//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTBL
    {
        public int PaymentID { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int PaymentStatusID { get; set; }
        public int OrderID { get; set; }
    
        public virtual PaymentStatusLookup PaymentStatusLookup { get; set; }
        public virtual CustomerOrder CustomerOrder { get; set; }
    }
}
