//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingTBL
    {
        public int TrackingID { get; set; }
        public Nullable<int> PickupBranchID { get; set; }
        public Nullable<int> ShippingBranchID { get; set; }
        public int OrderStatusID { get; set; }
        public int OrderID { get; set; }
    
        public virtual OrderStatusLookup OrderStatusLookup { get; set; }
        public virtual CustomerOrder CustomerOrder { get; set; }
    }
}
